# 00. PyTorch Fundamentals
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [3]:
import torch
import pandas
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.9.1+cu111


## Introduction to tensors

### Creating tensors

In [13]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [14]:
scalar.ndim

0

In [15]:
# Get tensor back as Pythin int
scalar.item()

7

In [16]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [18]:
vector.ndim

1

In [19]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [21]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [23]:
MATRIX[1][1]

tensor(10)

In [24]:
MATRIX[1,1]

tensor(10)

In [27]:
# TENSOR
TENSOR = torch.tensor([[[4, 5, 7],
                        [3, 6, 8],
                        [ 9, 7, 5]],
                      
                       [[1, 2, 4],
                        [9, 6, 5],
                        [1, 2, 3]]
                      ])
TENSOR

tensor([[[4, 5, 7],
         [3, 6, 8],
         [9, 7, 5]],

        [[1, 2, 4],
         [9, 6, 5],
         [1, 2, 3]]])

In [28]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([2, 3, 3]))

### Random tensors

In [33]:
### Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5441, 0.5777, 0.5268, 0.2589],
        [0.5138, 0.2979, 0.2825, 0.8271],
        [0.2729, 0.8411, 0.4133, 0.2881]])

In [34]:
random_tensor.ndim, random_tensor.shape

(2, torch.Size([3, 4]))

In [35]:
# Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([3, 224, 224]))

### Zeros and ones

In [38]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [42]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
ones.dtype

torch.float32